chore: make twitter and github links to open in new tab
ixahmedxi/noodle pull request #225
Opened 2023-07-10 14:34 UTC by i-naeem

Ads `_target=blank` to Twitter and Github link to open them in new tab.

2023-07-10 20:08 UTC, ixahmedxi requested changes

2023-07-10 20:08 UTC, ixahmedxi commented on apps/web/src/components/Navbar.tsx
> +              target="_blank"
Please add `rel="noreferrer noopener"` to the elements as well

2023-07-10 20:08 UTC, ixahmedxi commented on apps/web/src/components/Navbar.tsx
> +              target="_blank"
same here

2023-07-12 10:37 UTC, i-naeem commented on apps/web/src/components/Navbar.tsx
> +              target="_blank"
I have added that too you can check again :)

2023-07-12 10:38 UTC, i-naeem commented on apps/web/src/components/Navbar.tsx
> +              target="_blank"
yeah same here, I have added the `rel="noreferrer noopener"` too

2023-07-12 19:07 UTC, ixahmedxi submitted a review, later dismissed

2023-07-12 19:20 UTC, ixahmedxi approved these changes

2023-07-12 19:20 UTC, merged