feat(docs): added links to oauth github tokens and nx cloud
ixahmedxi/noodle pull request #243
Opened 2023-07-12 20:09 UTC by antoniobfm

A small improvement that can make the setup a little faster

2023-07-16 15:49 UTC, Johnmiicheal reviewed
👌

2023-07-16 18:24 UTC, ajitzero commented on CONTRIBUTING.md
> +You will also need to configure [oauth github tokens](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens) to be able to use the authen
```suggestion
You will also need to configure [GitHub OAuth tokens](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens) to be able to use the authentication functionality of Noodle.
```

Hi, could also please fix these minor typos?

2023-07-16 18:24 UTC, ajitzero commented on CONTRIBUTING.md
> +Also, if you want your own personal [nx cloud](https://cloud.nx.app/) instance, you will need to create a project on nx cloud and replace the default read only token provided.
```suggestion
Also, if you want your own personal [Nx Cloud](https://cloud.nx.app/) instance, you will need to create a project on Nx Cloud and replace the default read-only token provided.
```
And this as well.

2023-07-16 22:17 UTC, ajitzero approved these changes

2023-07-31 23:23 UTC, ixahmedxi requested changes
We have moved to clerk for authentication now which doesn't need github oauth tokens unless you want to move it to production which you can't under our license (unless it's us). 

So I would like to have some kind of instruction about setting up clerk's environment variables.

2023-08-01 17:36 UTC, antoniobfm commented
> We have moved to clerk for authentication now which doesn't need github oauth tokens unless you want to move it to production which you can't under our license (unless it's us).
> 
> So I would like to have some kind of instruction about setting up clerk's environment variables.

Ok, I will take a look into that!

2023-08-01 20:59 UTC, antoniobfm reviewed
I've modified the document to include clerk instead of github oauth tokens and a little tutorial on how to configure it.

What do you think?

2023-08-05 10:01 UTC, ixahmedxi approved these changes

2023-08-05 10:01 UTC, merged