Allow sidemenu to be toggled
ixahmedxi/noodle pull request #288
Opened 2023-08-12 22:49 UTC by gedeondoescode

This pull request is an attempt to fix #280.

2023-08-17 06:16 UTC, ixahmedxi requested changes

2023-08-17 06:16 UTC, ixahmedxi commented on apps/web/src/layouts/dashboard/index.tsx
> +  function SideMenuToggle() {
It's not advised to declare components inside of components because they will be created on every re-render. I would advise just doing something like this where you are using the `SideMenuToggle` component.

```jsx
<Button
  type="button"
  variant="muted"
  size="icon"
  onClick={() => {
    setIsMaximized(prev => !prev)
  }}
>
  <Icon name={isMaximized ? 'panel-left-close' : 'panel-left-open'} />
</Button>

2023-08-17 06:16 UTC, ixahmedxi commented on apps/web/src/layouts/dashboard/feedback.tsx
> +// eslint-disable-next-line @typescript-eslint/no-explicit-any
Type the component props

2023-08-17 19:23 UTC, gedeondoescode commented on apps/web/src/layouts/dashboard/index.tsx
> +  function SideMenuToggle() {
Will do

2023-08-17 19:38 UTC, gedeondoescode commented on apps/web/src/layouts/dashboard/feedback.tsx
> +// eslint-disable-next-line @typescript-eslint/no-explicit-any
made it into a boolean type

2023-09-04 21:10 UTC, gedeondoescode commented
closed in favor of #312.

2023-09-04 21:10 UTC, closed without merging